### ISSUE TITLE
Error when player exits.

### ISSUE THREAD

**Issue by Mcayear** [MemoriesOfTime/RsNPC#34]
```
2022-11-02 08:10:41.838 [main] INFO  - §bchumengguihuen§f[/172.18.0.1:36750] Quit game, because: Disconnected from Server
2022-11-02 08:10:41.841 [main] FATAL - Exception while invoking run
java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because the return value of "cn.nukkit.OfflinePlayer.getName()" is null
	at cn.nukkit.OfflinePlayer.isOp(OfflinePlayer.java:98) ~[PowerNukkitX.jar:?]
	at cn.nukkit.OfflinePlayer.setOp(OfflinePlayer.java:103) ~[PowerNukkitX.jar:?]
	at com.smallaswater.npc.tasks.PlayerPermissionCheckTask.onRun(PlayerPermissionCheckTask.java:35) ~[RsNPC-2.2.0-PNX.jar:?]
	at cn.nukkit.scheduler.Task.run(Task.java:52) ~[PowerNukkitX.jar:?]
	at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:100) [PowerNukkitX.jar:?]
	at cn.nukkit.scheduler.ServerScheduler.runTasks(ServerScheduler.java:312) [PowerNukkitX.jar:?]
	at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:293) [PowerNukkitX.jar:?]
	at cn.nukkit.Server.tick(Server.java:1508) [PowerNukkitX.jar:?]
	at cn.nukkit.Server.tickProcessor(Server.java:1279) [PowerNukkitX.jar:?]
	at cn.nukkit.Server.start(Server.java:1239) [PowerNukkitX.jar:?]
	at cn.nukkit.Server.<init>(Server.java:894) [PowerNukkitX.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:160) [PowerNukkitX.jar:?]
```
Plugin version: RsNPC-2.2.0-PNX.jar

Server version: PowerNukkitX 1.19.40 r2

**Comment by lt-name** [comment]
已修复，请下载最新快照
