### ISSUE TITLE
在PNX报错

### ISSUE THREAD

**Issue by Mcayear** [MemoriesOfTime/RsNPC#37]
### 服务器信息
```
11:47:43 [INFO ] 插件 (43)：PowerNukkitX v1.20.0-r2, AntiShield v0.0.1, VersionCheck v0.0.1, EssentialsNK v1.9.2, spark v1.9.44, MultiWorld v1.1, ServerInfo v1.0.7, HealthAPI v1.3.1, FakeInventories v1.0.4, ScoreboardPlugin v1.0, SignIn v1.1.8, CloseCheckMovement v1.0-SNAPSHOT, PHPBN v1.0.0, Knickers v2.2.3, Tips v2.1.2, NJSUtil v1.0.0, AuthorizedOP v1.0.0, Wilds v1.0.0, SetJoinQuitMessage v1.0.5, NoSpaceInName v1.1.0, LuckDraw v1.4.5, MoTaCustom v1.0.0, ResourcePack v1.0.0, GUI v1.15.1, MagicItem v1.0.1, DbLib v1.0.1, TrashBin v1.0.0, KotlinLib v1.3.72, Friends v1.2.5, EconomyEvent v1.0.1, FastAsyncWorldEdit vunknown, EconomyAPI v2.0.2, TipsVeriable v1.0.2, MarryN v0.0.12, LLSELib v0.0.5, RsNPC v2.3.2-PNX-SNAPSHOT, FuturePlots v3.3.4-SNAPSHOT, RSTask v1.8.2, BlocklyNukkit v1.2.9.11, MemoriesOfTime-GameCore v1.6.10-PNX, NukkitPanel v1.19, NWorldProtect v0.0.1, TaskUse v1.0.9
>....11:47:48 [INFO ] 此服务器正在运行 Nukkit 1.20.0-r2 「」API 版本 1.0.14 的 Minecraft: BE v1.20.0 (协议版本 589)
```

### 错误日志
```
11:46:28 [ERROR] 更新世界 "阿兹克特" 时出现错误：java.lang.NullPointerException: Cannot invoke "String.getBytes(java.nio.charset.Charset)" because "string" is null
        at cn.nukkit.utils.BinaryStream.putString(BinaryStream.java:813)
        at cn.nukkit.network.protocol.EmotePacket.encode(EmotePacket.java:40)
        at cn.nukkit.network.protocol.DataPacket.tryEncode(DataPacket.java:55)
        at cn.nukkit.Server.broadcastPacket(Server.java:1731)
        at com.smallaswater.npc.entitys.EntityRsNPC.onUpdate(EntityRsNPC.java:154)
        at cn.nukkit.level.Level.doTick(Level.java:1260)
        at cn.nukkit.Server.checkTickUpdates(Server.java:1203)
        at cn.nukkit.Server.tick(Server.java:1289)
        at cn.nukkit.Server.tickProcessor(Server.java:1152)
        at cn.nukkit.Server.start(Server.java:1133)
        at cn.nukkit.Server.<init>(Server.java:960)
        at cn.nukkit.Nukkit.main(Nukkit.java:160)
java.lang.NullPointerException: Cannot invoke "String.getBytes(java.nio.charset.Charset)" because "string" is null
        at cn.nukkit.utils.BinaryStream.putString(BinaryStream.java:813) ~[PowerNukkitX.jar:?]
        at cn.nukkit.network.protocol.EmotePacket.encode(EmotePacket.java:40) ~[PowerNukkitX.jar:?]
        at cn.nukkit.network.protocol.DataPacket.tryEncode(DataPacket.java:55) ~[PowerNukkitX.jar:?]
        at cn.nukkit.Server.broadcastPacket(Server.java:1731) ~[PowerNukkitX.jar:?]
        at com.smallaswater.npc.entitys.EntityRsNPC.onUpdate(EntityRsNPC.java:154) ~[RsNPC-2.3.2-PNX-SNAPSHOT.jar:?]
        at cn.nukkit.level.Level.doTick(Level.java:1260) ~[PowerNukkitX.jar:?]
        at cn.nukkit.Server.checkTickUpdates(Server.java:1203) [PowerNukkitX.jar:?]
        at cn.nukkit.Server.tick(Server.java:1289) [PowerNukkitX.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:1152) [PowerNukkitX.jar:?]
        at cn.nukkit.Server.start(Server.java:1133) [PowerNukkitX.jar:?]
        at cn.nukkit.Server.<init>(Server.java:960) [PowerNukkitX.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:160) [PowerNukkitX.jar:?]
```

**Comment by lt-name** [comment]
6月22日修复了，请确保使用的是最新快照版本

**Comment by Mcayear** [comment]
用的是#40次构建
https://ci.lanink.cn/view/Memories%20Of%20Time/job/RsNPC/job/PNX/40/

**Comment by lt-name** [comment]
从报错堆栈跟踪看，你用的并不是你所说的版本
最新快照的第154行不涉及发包
