### ISSUE TITLE
无法创建NPC

### ISSUE THREAD

**Issue by Chenyu550** [MemoriesOfTime/RsNPC#38]
创建时就出现未知错误，控制台报错如下，之前创建好的也加载不出来了
PMIE1.20.50
java.lang.IllegalStateException: EntityRsNPC must have a valid skin set
        at cn.nukkit.entity.EntityHuman.spawnTo(EntityHuman.java:100) ~[patched.jar:?]
        at com.smallaswater.npc.entitys.EntityRsNPC.spawnTo(EntityRsNPC.java:275) ~[?:?]
        at cn.nukkit.entity.Entity.spawnToAll(Entity.java:834) ~[patched.jar:?]
        at com.smallaswater.npc.data.RsNpcConfig.checkEntity(RsNpcConfig.java:385) ~[?:?]
        at com.smallaswater.npc.command.sub.CreateSubCommand.execute(CreateSubCommand.java:67) ~[?:?]
        at com.smallaswater.npc.command.base.BaseCommand.execute(BaseCommand.java:44) ~[?:?]
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:136) ~[patched.jar:?]
        at cn.nukkit.Server.dispatchCommand(Server.java:1390) ~[patched.jar:?]
        at com.smallaswater.npc.utils.FormHelper.lambda$sendCreateNpc$1(FormHelper.java:59) ~[?:?]
        at cn.lanink.gamecore.form.windows.AdvancedFormWindowCustom.callResponded(AdvancedFormWindowCustom.java:58) ~[?:?]
        at cn.lanink.gamecore.form.windows.AdvancedFormWindowCustom.onEvent(AdvancedFormWindowCustom.java:74) ~[?:?]
        at cn.lanink.gamecore.form.WindowListener.onPlayerFormResponded(WindowListener.java:54) ~[?:?]
        at org.lanternpowered.lmbda.Lmbda$2.accept(Unknown Source) ~[patched.jar:?]
        at cn.nukkit.plugin.LambdaEventExecutor.execute(LambdaEventExecutor.java:5) ~[patched.jar:?]
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:15) ~[patched.jar:?]
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:69) ~[patched.jar:?]
        at cn.nukkit.Player.handleDataPacket(Player.java:2321) ~[patched.jar:?]
        at cn.nukkit.network.session.RakNetPlayerSession.serverTick(RakNetPlayerSession.java:36) ~[patched.jar:?]
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:26) ~[patched.jar:?]
        at cn.nukkit.network.Network.processInterfaces(Network.java:142) ~[patched.jar:?]
        at cn.nukkit.Server.b(Server.java:1126) ~[patched.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:1131) ~[patched.jar:?]
        at cn.nukkit.Server.start(Server.java:636) ~[patched.jar:?]
        at cn.nukkit.Server.<init>(Server.java:399) ~[patched.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:25) ~[patched.jar:?]
        at nukkit.pm1e.launcher.Main.lambda$start$0(Main.java:71) ~[?:?]
        at java.lang.Thread.run(Thread.java:842) [?:?]

**Comment by lt-name** [comment]
请检查皮肤文件

**Comment by Chenyu550** [comment]
> 请检查皮肤文件，另外检查下所使用的版本是否为PM1E分支

分支是对的，现在必须用自己的皮肤了吗？以前都是用默认皮肤的

**Comment by lt-name** [comment]
更新到最新快照试试

**Comment by Chenyu550** [comment]
> 更新到最新快照试试

正常了，感谢
